### ISSUE TITLE
Lesson 3 (Weather Sensor): Rewrite in MicroPython

### ISSUE THREAD

**Issue by tdeknecht** [StateFarm-STEM/hablogger#1]
Rewriting Lesson 3 in MicroPython. Using this issue for collaboration as needed.

**Comment by pankonen** [comment]
Goals:

- Have weather module wired up on the breadboard
- Working code echoing temperature, pressure, (humidity if using the bmp280)
- Code is well commented explaining whats going on to help teachers work though on their time with the class
- Run from students USB port
Bonus:
- Troubleshooting steps

**Comment by gregdirst** [comment]
@pankonen  I am unable to assign tasks or push code

**Comment by pankonen** [comment]
Not sure that's weird. Are you logged in? I have everyone as a maintainer I believe. It is assigned via a GitHub group but that shouldn't matter. Is anyone else having issues?

**Comment by tdeknecht** [comment]
No issues here. Able to push branches and so other Issue related work.

**Comment by pankonen** [comment]
Should be fixed now @gregdirst, sorry about that

**Comment by gregdirst** [comment]
@pankonen I am probably doing something wrong, but I still cannot seem to do anything. I can't create a pull request and I can't add files directly. When I tried to accept that invite once I found it, it said it was 1 day past expiration (-1). Maybe I still don't have access?

**Comment by pankonen** [comment]
> @pankonen I am probably doing something wrong, but I still cannot seem to do anything. I can't create a pull request and I can't add files directly. When I tried to accept that invite once I found it, it said it was 1 day past expiration (-1). Maybe I still don't have access?

Looks like you were not a member which is weird. You were the other day? I've added you, you should see the invitation.

**Comment by tdeknecht** [comment]
Closed via PR https://github.com/StateFarm-STEM/hablogger/pull/13
